app_python_base_dir: 'opt/app_python'
app_python_name: 'app_python'
app_python:
  image: devops
  tag: latest
  registry: tasneem
  external_port: 1337
  internal_port: 5000
app-python_full_wipe: false